# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 189cb882a52021fd86f792993ab9c14d33b3853ca154a8c2d6e4341d50206ec7b7d75d0f5aecad0220e36c8152e6e4c68d4c8b319253d01fe258596c094a10f4

test:
  secret_key_base: d50213248623515535c438dab6f49b00f597de80ea2dcaaf7712ee7eb57bb31e788f607a5a42a4d8848cfe251ba90d342697b3beb15b3a7a8382bcd17269b032

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
